<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);WFO1000;NU1510</NoWarn>
    <RootNamespace>CymaticLabs.InfluxDB.Studio</RootNamespace>
    <AssemblyName>InfluxDBStudio</AssemblyName>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InfluxData.Net" Version="8.0.1" />
    <PackageReference Include="Scintilla5.NET" Version="7.0.0" />
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
  </ItemGroup>
</Project>